---
msi_dir: "%SYSTEMDRIVE%\\OpenStack\\MSIs"
log_dir: "%SYSTEMDRIVE%\\OpenStack\\Log"
hyperv_cinder_msi: "HyperVCinderVolume.msi"
cinder_database_address: "{{ kolla_internal_fqdn }}:{{ database_port }}"
cinder_database_name: "cinder"
cinder_database_user: "{% if use_preconfigured_databases | bool and use_common_mariadb_user | bool %}{{ database_user }}{% else %}cinder{% endif %}"
